namespace: fleet-mc-helm-example
targetCustomizations:
- name: dev
  helm:
    values:
      replication: false
  clusterSelector:
    matchLabels:
      env: dev

- name: test
  helm:
    values:
      replicas: 1
  clusterSelector:
    matchLabels:
      env: test
- name: test3
  helm:
    values:
      replicas: 1
  clusterSelector:
    matchLabels:
      env: test3


- name: prod
  helm:
    values:
  #    serviceType: LoadBalancer
      replicas: 1
  clusterSelector:
    matchLabels:
      env: prod
